### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by serjkazhura** [Envek/aws-sam-typescript-layers-example#12]
Hi everyone, thank you for a really neat solution that you have provided! 

I am working on a project at the moment, and I want to leverage your solution. 

Would it be possible to add a LICENSE file to the project? For example, I am always using [MIT License](https://github.com/serjkazhura/sam-lambda-cicd/blob/main/LICENSE) for my projects. 

This way I can make a proper attribution to your project and give you the credit that you deserve.

Thank you!

**Comment by Envek** [comment]
Hey, thank you for pointing this out! This repo contains result of project generation by [AWS SAM CLI](https://github.com/aws/aws-sam-cli) (which source is licensed under Apache-2.0, but I have no idea whether it is applicable to its, um, output) and my own work on top of it.

Declared this project as MIT licensed, as I also tend to use this license for open-source work.

P.S> You're also welcome to contribute to [cookiecutter-aws-sam-typescript-layers](https://github.com/Envek/cookiecutter-aws-sam-typescript-layers) which is a template to generate projects like this example, but from scratch.
